//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.FriendLists = new HashSet<FriendList>();
            this.FriendLists1 = new HashSet<FriendList>();
            this.FriendListRequests = new HashSet<FriendListRequest>();
            this.FriendListRequests1 = new HashSet<FriendListRequest>();
            this.LogInTokens = new HashSet<LogInToken>();
            this.UserHobbyMappings = new HashSet<UserHobbyMapping>();
            this.UserLocationHistories = new HashSet<UserLocationHistory>();
            this.UserMatchings = new HashSet<UserMatching>();
            this.UserMatchings1 = new HashSet<UserMatching>();
            this.UserNotifications = new HashSet<UserNotification>();
            this.UserPhotoes = new HashSet<UserPhoto>();
            this.UserStatus = new HashSet<UserStatus>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public Nullable<System.DateTime> LastActivityToNow { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<FriendList> FriendLists { get; set; }
        public virtual ICollection<FriendList> FriendLists1 { get; set; }
        public virtual ICollection<FriendListRequest> FriendListRequests { get; set; }
        public virtual ICollection<FriendListRequest> FriendListRequests1 { get; set; }
        public virtual ICollection<LogInToken> LogInTokens { get; set; }
        public virtual ICollection<UserHobbyMapping> UserHobbyMappings { get; set; }
        public virtual ICollection<UserLocationHistory> UserLocationHistories { get; set; }
        public virtual ICollection<UserMatching> UserMatchings { get; set; }
        public virtual ICollection<UserMatching> UserMatchings1 { get; set; }
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
        public virtual ICollection<UserPhoto> UserPhotoes { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UserStatus> UserStatus { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
