//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendListRequest
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string TargetUserID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser RequestingUser { get; set; }
        public virtual AspNetUser TargetUser { get; set; }
    }
}
