//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobby
    {
        public Hobby()
        {
            this.Hobby1 = new HashSet<Hobby>();
            this.UserHobbyMappings = new HashSet<UserHobbyMapping>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentHobbyID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Hobby> Hobby1 { get; set; }
        public virtual Hobby Hobby2 { get; set; }
        public virtual ICollection<UserHobbyMapping> UserHobbyMappings { get; set; }
    }
}
