//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipStatu
    {
        public RelationshipStatu()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
