//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string UserID { get; set; }
        public string Url { get; set; }
        public string Content { get; set; }
        public bool Read { get; set; }
        public System.DateTime CreationTime { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual NotificationCategory NotificationCategory { get; set; }
    }
}
