//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDatingCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatItem
    {
        public int ID { get; set; }
        public int ConversationID { get; set; }
        public string Content { get; set; }
        public int ContentTypeID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
    
        public virtual ChatConversation ChatConversation { get; set; }
    }
}
