//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDatingCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public string UserID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> InterestedInID { get; set; }
        public Nullable<int> ReligiousViewID { get; set; }
        public Nullable<int> RelationshipID { get; set; }
        public string About { get; set; }
        public string School { get; set; }
        public Nullable<bool> Graduated { get; set; }
        public string Work { get; set; }
        public string WorkPlace { get; set; }
        public Nullable<bool> ShareLocation { get; set; }
        public string Subtitle { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual InterestedIn InterestedIn { get; set; }
        public virtual RelationshipStatu RelationshipStatu { get; set; }
        public virtual ReligiousView ReligiousView { get; set; }
    }
}
